# Rest clients
DoughService/mp-rest/uri=http://localhost:8080/mock
DoughService/mp-rest/scope=jakarta.enterprise.context.ApplicationScoped
MeatService/mp-rest/uri=http://localhost:8080/mock
MeatService/mp-rest/scope=jakarta.enterprise.context.ApplicationScoped
OvenService/mp-rest/uri=http://localhost:8080/mock
OvenService/mp-rest/scope=jakarta.enterprise.context.ApplicationScoped
StoveService/mp-rest/uri=http://localhost:8080/mock
StoveService/mp-rest/scope=jakarta.enterprise.context.ApplicationScoped

# Slow down mocked services?
slowdown=true